### ISSUE TITLE
How to use `drives` as a personal seeding service?

### ISSUE THREAD

**Issue by josephmturner** [holepunchto/drives#30]
I'd like to run `drives` on a VPS to seed a hyperdrive. Ideally, this setup would:

1. automatically download changes made to the drive
2. seed the full, up-to-date drive
3. not require manually switching between downloading and seeding

My first pass looked like this:

```
drives download PUBLIC-KEY >> drives-download.log &
drives seed PUBLIC-KEY >> drives-seed.log &
```

However, attempting to run both commands at once resulted in the following error:

```
  const err = new Error('ELOCKED: File is locked')
              ^

Error: ELOCKED: File is locked
    at createLockError (/usr/local/lib/node_modules/drives/node_modules/random-access-file/index.js:249:15)
    at onopen (/usr/local/lib/node_modules/drives/node_modules/random-access-file/index.js:105:19)
    at FSReqCallback.oncomplete (node:fs:197:23) {
  code: 'ELOCKED',
  path: '/root/.drives/corestore/primary-key'
}

Node.js v18.13.0
```

What would you recommend?

**Comment by mafintosh** [comment]
Use simple-seeder, thats meant for this

**Comment by josephmturner** [comment]
> Use simple-seeder

Thank you!!! It works great!!!
